2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_setup.py:_flush():76] Current SDK version is 0.15.6
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_setup.py:_flush():76] Configure stats pid to 53648
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ferti\.config\wandb\settings
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ferti\Documents\RL_Modular\wandb\settings
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_deep_policy.py', 'program': 'c:/Users/ferti/Documents/RL_Modular/train_deep_policy.py'}
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\ferti\Documents\RL_Modular\wandb\run-20230725_015650-trjja7vt\logs\debug.log
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\ferti\Documents\RL_Modular\wandb\run-20230725_015650-trjja7vt\logs\debug-internal.log
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_init.py:init():547] calling init triggers
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {}
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_init.py:init():596] starting backend
2023-07-25 01:56:50,639 INFO    MainThread:53648 [wandb_init.py:init():600] setting up manager
2023-07-25 01:56:50,663 INFO    MainThread:53648 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=spawn, using: spawn
2023-07-25 01:56:50,671 INFO    MainThread:53648 [wandb_init.py:init():606] backend started and connected
2023-07-25 01:56:50,703 INFO    MainThread:53648 [wandb_init.py:init():697] updated telemetry
2023-07-25 01:56:50,815 INFO    MainThread:53648 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-07-25 01:56:52,381 ERROR   MainThread:53648 [wandb_init.py:init():756] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-25 01:56:52,767 ERROR   MainThread:53648 [wandb_init.py:init():1165] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Users\ferti\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\wandb_init.py", line 1147, in init
    run = wi.init()
  File "C:\Users\ferti\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-25 01:56:53,790 WARNING MsgRouterThr:53648 [router.py:message_loop():77] message_loop has been closed
